# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: Users
entries:
  - id: jakob
    model: authentik_core.user
    identifiers:
      username: jakob
    attrs:
      name: Jakob
      password: !Env JAKOB_PASSWORD
      email: !Env JAKOB_EMAIL
      type: internal
      groups:
        - !Find [
          authentik_core.group,
          [name, "Observability"],
        ]
        - !Find [
          authentik_core.group,
          [name, "Media"],
        ]
        - !Find [
          authentik_core.group,
          [name, "Public"],
        ]
  - id: masa
    model: authentik_core.user
    identifiers:
      username: masa
    attrs:
      name: Masa
      password: !Env MASA_PASSWORD
      email: !Env MASA_EMAIL
      type: internal
      groups:
        - !Find [
          authentik_core.group,
          [name, "Media"],
        ]
        - !Find [
          authentik_core.group,
          [name, "Public"],
        ]


