apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: internal
      namespace: traefik
  hostnames:
    - "adguard.blarc.my.id"
  rules:
    - backendRefs:
        - name: adguard-web
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /