apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users
  namespace: {{ .Release.Namespace }}
stringData:
  users.yaml: |
    users:
      {{- range .Values.users }}
      - name: {{ .name }}
        password: {{ .password | quote }}
      {{- end }}