apiVersion: v1
kind: Secret
metadata:
    name: alertmanager
    namespace: observability
stringData:
    NTFY_URL: ENC[AES256_GCM,data:mnfrXdLG88c3oOsCilcF7s77xWwWgZMDeX+vcT1qH9sbh7pCynCIHjWrhv+TG5Hg,iv:+Ut+KdB54kHnmCef7nkK11Vm/+BNm3EgwSxslZbOR8I=,tag:uwnwZSkI8PgfJdpGSnWy+A==,type:str]
    NTFY_USERNAME: ENC[AES256_GCM,data:gqdnA4aIlqNXoTPS,iv:JYK3dpowFFu85VhBykgcjwFN4uYOG+FbLq6bo/VltAU=,tag:0PyAN3Gd5wGq3iwtH5KOGg==,type:str]
    NTFY_PASSWORD: ENC[AES256_GCM,data:qhQhWA2/kS2hfJI6laCjofp9hL2Ylg==,iv:thzEPJsKnlN9e+XggK2UtjJqU9/Y5mBqO+cKK+X2xTY=,tag:AtM49NpEj1FXxgBF6XvySA==,type:str]
sops:
    age:
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa1BuVFBkSFNJUm4rY2Nu
            U3l3WHpIMmdyeklEUTBhcjF0cWZDbmljWHc4CmFtOW1FRmtIT1VMUXlGeG9FQWQ4
            R09aTFNYVW1CQ2lScE5RQUttUVltRzAKLS0tIEpyY1kxZUFRK2RxTWx2VDE0QWk1
            Tm5lRmpibWVxdnFyZnF0TTBjVkdFTjQKiZeELz1Y4VWWV+Bp1RTvg1dxa8q7Ty3H
            fno7KoEfacjSf01OlMlLiVbi/cicVrxKkA2MvozL+Pl2J0aZycMxiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T18:26:06Z"
    mac: ENC[AES256_GCM,data:cz07WT3Sri1hXJV+lfS1+eJM+xsee3ziRD42T/MxsCNMimaT89pWNY4naelKjY8znqv+44FPuPFQql6r9ctbH8VlQndzVH39k6GiQLjPtSvUqxS64IF6hSNtQOcx3bG2xTkxR8Kquo00u7GJYMkFYivGwCeBbyRgga/WPBCCJRk=,iv:XR+jlI2LUsUh02f3RVvEX1l/q2dlo8udzRgDcf27jsA=,tag:dksEdB21Aptpj5hXEjvMHA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
