apiVersion: v1
kind: Secret
metadata:
    name: alertmanager
    namespace: observability
stringData:
    NTFY_URL: ENC[AES256_GCM,data:HA6nbseDdhss5sBC9A+mLPIsAyhu8AAx5nw=,iv:bLv/whrI1uw7k0nT2A7nVqvHzq0ryivAN04qkRwTSiY=,tag:EJuTnHD3ZX6Sch+1FypipA==,type:str]
    NTFY_USERNAME: ENC[AES256_GCM,data:gqdnA4aIlqNXoTPS,iv:JYK3dpowFFu85VhBykgcjwFN4uYOG+FbLq6bo/VltAU=,tag:0PyAN3Gd5wGq3iwtH5KOGg==,type:str]
    NTFY_PASSWORD: ENC[AES256_GCM,data:qhQhWA2/kS2hfJI6laCjofp9hL2Ylg==,iv:thzEPJsKnlN9e+XggK2UtjJqU9/Y5mBqO+cKK+X2xTY=,tag:AtM49NpEj1FXxgBF6XvySA==,type:str]
sops:
    age:
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa1BuVFBkSFNJUm4rY2Nu
            U3l3WHpIMmdyeklEUTBhcjF0cWZDbmljWHc4CmFtOW1FRmtIT1VMUXlGeG9FQWQ4
            R09aTFNYVW1CQ2lScE5RQUttUVltRzAKLS0tIEpyY1kxZUFRK2RxTWx2VDE0QWk1
            Tm5lRmpibWVxdnFyZnF0TTBjVkdFTjQKiZeELz1Y4VWWV+Bp1RTvg1dxa8q7Ty3H
            fno7KoEfacjSf01OlMlLiVbi/cicVrxKkA2MvozL+Pl2J0aZycMxiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T17:36:37Z"
    mac: ENC[AES256_GCM,data:AxrDedpV8VM0KCEhJYgK0ADmIOJnflbbwpwzholdLHq/DtvauMvtdqAct/BkQ2PYz708DtnN+j1w09W4mFo1pisaN8GgT2IUYua4/SggW9jdaVkknQwb6xDvk7Z3IFYN8cLaiGFYsLv2tQEaBmBp41RYs/EaOTvCXZqXsSHvbgQ=,iv:Lzo9IWRCx2ruSUrwGzNWJl0lQxBAQtlpAjOOWXkvA38=,tag:q3YJva3sOW5w2OoIBo0jSA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
