authentik:
    authentik:
        secret_key: ENC[AES256_GCM,data:f7FNlD4hSVtljDu2qg0vGCXEPSDcO5XQbLMOqKMhFx7TFeKNeecSF74VIARGI3JtlHFkSZIrGQA=,iv:5U2sGOgUrSAFHyiMDQyJCLQ7UHh2E33ODALfAwueSig=,tag:1V9QLpTwdEjWmRdyTtS+zQ==,type:str]
    providersSecrets:
        PAPERLESS_NGX_PROVIDER_CLIENT_ID: ENC[AES256_GCM,data:dmBreLmkOOJeIpCpDHd6p8jSvhaE4U+EpM+h4AbtxjIx96lK2H/LIA==,iv:iFRu1rUPmHaeZvXYE1TCM+10OW9GC/+86yosh6G6ExI=,tag:GtvpzJ30NT+VDd/fBQG5qw==,type:str]
        PAPERLESS_NGX_PROVIDER_CLIENT_SECRET: ENC[AES256_GCM,data:Z1PPckaLsggb3a0zuhWe4fNzxDzTE3VSRlKubn5f3WktGdrCVdxp6nGQxXZlUhvduRF9hO3tz3P4xSzNSKz2iFMwUgmrzY3B5gNoHQ0NtGg9qbtlSrHWjSDPo/pY4Y5YjJNmIe61H1h6VkedqnqkMrFzfoDRMfUOwyyFOxOZNA8=,iv:DIz73rUXRLtJPQFOFboJIGCx9EcVS1DHlFtt2rmd4R4=,tag:aPwlmruUpQXpdG9APLB3xw==,type:str]
        GRAFANA_PROVIDER_CLIENT_ID: ENC[AES256_GCM,data:BVjqqjMu1B+Q8GT4F+ocQPvPOOneS1q08pqIVMVs/Oa3s3UV2DQoNA==,iv:jKmeuWQeNondUS4PyRQeY4jd1NPXZCQlvSX0KdHJH+A=,tag:JYID5KGq/c4wEim5Y1GacQ==,type:str]
        GRAFANA_PROVIDER_CLIENT_SECRET: ENC[AES256_GCM,data:SUR4EOgysWNA6/lN4piAzbJgdy2WEjODLM5WngsiQHi0/RjfwyhSm6pqVe1k37q2ggay/lffE6x9/DhMMx5PlEbDgMETIqjrh5AGg1bh4GKvVwt+uCTsQUzOe+Aqq8Z876TUJr1huSQ/MPZtesrQSdUfMMKdZkiP7g+A9Y8XjNY=,iv:f4ipqEZYLpdVxK6A2NR7PKoh/2yEOlpGEyzLs/v6QkA=,tag:OsRhDXnFtjb6oeZNNnxjAg==,type:str]
        AUDIOBOOKSHELF_PROVIDER_CLIENT_ID: ENC[AES256_GCM,data:VxD2eHs7ZUKtcIcRQ4+oI+P6NxMRyz3nSaqvZcITJtgR1IftMyXWfg==,iv:vO2YY73WrMowijBzfR+OroyExwXevA7lBePs1/uQ8Hc=,tag:VD3dQz1pBjDjVJlbWVOy1w==,type:str]
        AUDIOBOOKSHELF_PROVIDER_CLIENT_SECRET: ENC[AES256_GCM,data:LpE5DwpKJUi3Xe0e9SO8PEpSnsJrpZyDkKemUmFYCsycotvgavjlw53BNPyc7biqNs4xi6+F+Q8Wc9ZuloXdMHIp+OcdA9lsVkZm3/PO6mvTUiJ/Vbd0u2Gy76Zv2ZkuVnvtvv6CxI1qR1vI1HO56Bvwej3im8mFSot2Jn0ag0g=,iv:OUKsaJbpdbNtySXSbva1gsUBjIke/+TjlIrtaNPGKmU=,tag:rkXOedXhmo2eBCBZffj55A==,type:str]
    users:
        - username: ENC[AES256_GCM,data:q1YQ9dM=,iv:zBKnfFsVMSarpOGFyHlpcEt7cz4ZtszGs3DkZ9uYF3A=,tag:ijP/bZuHsrJY9pQEnktm+g==,type:str]
          password: ENC[AES256_GCM,data:EGIJpmegd+RMlcXlSL1ZbHLC,iv:cnTU1mIxPfpx89/6tbOzYt86s5zlkkqzwoDSWXW/BUU=,tag:P1Nx7r2FXGDOdRTHY13Dyw==,type:str]
        - username: ENC[AES256_GCM,data:EV2D6Q==,iv:YF5/X2VOCmtG20dg6spxAKmP4e9eHin21j8DVsZlIko=,tag:dfLxrrx5MQpCP328IjIMmg==,type:str]
          password: ENC[AES256_GCM,data:44ak74WbiYoiFR7w,iv:vH3BgCmgC9dU7s/NhwkVSrEqCxm9E81wNlIXsO0LJ/g=,tag:fITib7C8k11JgavpyswzVQ==,type:str]
sops:
    age:
        - recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ1dxWXJRVFUrb2QvYkx1
            U0R4MXVYeExVS01XUndoakcveklGZ0Noc2dBCkFZamJUbUYxRllPcndLMEdoNFN6
            T1QrSVhadnhXWXBOekJEM0VGQW9oN2cKLS0tIE0wdXROR1lpdGlDeE0yekdrWTg1
            UGFLWHBNRjFybGhJMjhnOVd4dlQ1M1kKzxu7reB7uSbiv2CZn/iTmhtCFWh9xyCu
            +nI0DMZkDRHWmx4GWZYCXoVC0suJNwpyeTYYP3719wQlRK4Kziwv5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteEFORGgyMUNnZ1YrdzND
            S0NEck5HeElOVTBOUE1xeFZQeFJOYXUwQnlFCkJZUkdaYTgxNUZuN2FqKzhkTzVY
            YXdaQmxqWXQraytzZTU1R3FmUzB5ME0KLS0tIEJxOENTTWFlRXlZUDhCMktxTjdG
            M3NvOE04NXpZaXV5MmpvOXNQZ1AvMTAKoLZMR/x+crsJiJkh2hrXegnStbAivKb1
            YAYiSxFM2Z3m5JXeYlXSFR0KVX/7sZ7YA5ajBaL58nI7YHzY/ldPPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T19:58:43Z"
    mac: ENC[AES256_GCM,data:2Ij3x5KARgGFRNsS9M5i7r2lMt+axs5URtvPrPJbg/Qk1wZIIClxHKeQfMqmjBcirBoEWzOUPvSdO3MNRqmgm3TVzu6q0rFgYZiO7hrCedlIgn/7Jtk0elqrntkbXZOkTgm11e785uSbhgtauVzWCSM7SMIrWl9tcpPkCUN08oo=,iv:bSA7pK0cYKsDunyu9QGp++ezLfSCaPy0yzEpVpQ5xAY=,tag:Cj2VYyuR0UWEhRE4gk53CA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
