apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry
  namespace: storage
spec:
  parentRefs:
    - name: gateway-internal
      namespace: gateway
  hostnames:
    - "registry.int.blarc.my.id"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v2
      backendRefs:
        - name: docker-registry
          port: 5000
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: registry-ui
          port: 8080
