apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-mailserver
spec:
  secretName: docker-mailserver-certificate
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - mail.blarc.my.id
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer