apiVersion: v1
kind: Secret
metadata:
    name: ntfy
    namespace: ntfy
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:ECyEjM8YpcBqWNC4yPtift0IFjk6qv4/XDZQHlGOg5mMqHcKpJXv1rkPoBwfgpUC3piZEgpZ8kckn4ZQnZJ4/SLugxO8LWZQw2feO2bYWm0e+fINA5Qie6HZIFN/BPo6GuBszjSeZUcu5VDbP4otCCrWFPXkXjr6UdAxcM+RrJEuaTu5TbR2D9B3Dy94LL+73ao=,iv:ZrpBxPhxaSWPhQ9t3mMNe6sXbKzCVKYVgUiPdWrcJb0=,tag:QEkatsKriz1poVa2utrQQg==,type:str]
sops:
    age:
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UkVGQzBSeFFTMGpBMkhu
            cXVtSVV2L0xPai9jRjIrcDdqU0YvcEp3MmpnCmlVTk90N3JKSHVEVXM0ZEZSWmtM
            QUZ1RzNBbFF3RUZ3bEg1ZVlXRkw3T0EKLS0tIEJJSUJBVEkrRjRiL2hIWlMyOEdU
            aEJNSFl3MmY3TFpDeEVCVnZkbjNFZm8KjntDdRG+XC7hX3MZ+SdfasbWEYaT5I1/
            8hlVjeYFBio+xFuonGy1tV/4csy50DZ27QC5DuoqRdB5jiKikoSObg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:10:11Z"
    mac: ENC[AES256_GCM,data:SgIySRQa7ilXOmO/wnaKgNS2nX5dex0xcJO5IHPIG+/21qBsPX0zEDmQQAisoUNLD6HdrKOs7SAlB0zULuUBybNG9x5gF5yEWgQ9RpltXpNT0umVkkQIHBmRZhK95fm9X1L/aCm1XvD0xeO1/fSGhNhtpLjA+fjTn1FGTYSlgU4=,iv:GMIRzJ9ffhb37aSWiwMBUKUup+9RkxZ/wwWWuRw8E2Y=,tag:LO3TVAJ0mVcdqM2xOVRGUA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
