apiVersion: v1
kind: Secret
metadata:
    name: ntfy
    namespace: ntfy
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:TwslWFcXpOEU9hMrLaDNAQltFjSL3JdQLOHAwGOi5rCX236SJS/t6xqa53HvCnfKNx4cY06G9hdZFc5QMbF7H0l9Jsh4iJwh0SBKC10ZG9MQPIA0s61rxcMcX3QdmQT4WpbdMyMkY5cCarGRU+DWvEBwvBcm8/8tGPoFvZmEculCNTu7MxkbO2OPy65UZ+LbEZgGETou6wuguUoIUEKJtz+8FZlBFYWs/Kl8vRSjOXbxkSCDU+An9YeiarZzyIsKHyqa65xhEws3kmWkCou+AUTsBI8dOlHuxNU36fZ6+lct,iv:lhOdIlC4juNBYKkYC2hKRbvYw44EuWdb6wspv6LnKUQ=,tag:CyVpUNBYTOG4myCxFZE6Ug==,type:str]
sops:
    age:
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UkVGQzBSeFFTMGpBMkhu
            cXVtSVV2L0xPai9jRjIrcDdqU0YvcEp3MmpnCmlVTk90N3JKSHVEVXM0ZEZSWmtM
            QUZ1RzNBbFF3RUZ3bEg1ZVlXRkw3T0EKLS0tIEJJSUJBVEkrRjRiL2hIWlMyOEdU
            aEJNSFl3MmY3TFpDeEVCVnZkbjNFZm8KjntDdRG+XC7hX3MZ+SdfasbWEYaT5I1/
            8hlVjeYFBio+xFuonGy1tV/4csy50DZ27QC5DuoqRdB5jiKikoSObg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T17:31:31Z"
    mac: ENC[AES256_GCM,data:LdWmabM3aU9JJL0onYCa574XCL7uCA90GbmVxetOUMIGBluNvlcTdN8z3G8DEL+HSa+rtVb3d7aSUrUu0a/8SsBQ/4eKnVaKtPJ3H+qYxcU9claIQq4Vgak0jSExY2WUw1Bi3l+JDgS62T3IFbmZnihlQucSPFt3gLP07ZFsyfc=,iv:1fY2alUNzKSsEySzXellHkaGhng0gzv/K7wh6Q7CIVY=,tag:GcMOPvtsmZFa7Z/6roppPQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
