apiVersion: v2
dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.27.0
description: Helm chart to deploy cloudnative-pg
name: cloudnative-pg
version: 1.0.0
