podinfo:
  fullnameOverride: podinfo
  service:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: "192.168.1.223"
  httpRoute:
    enabled: true
    hostnames:
      - podinfo.int.blarc.my.id
    parentRefs:
      - name: gateway-internal
        namespace: gateway