apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mosquitto
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "mosquitto.blarc.my.id"
  rules:
    - backendRefs:
      - name: mosquitto
        port: 8123
      matches:
        - path:
            type: PathPrefix
            value: /
