apiVersion: v2
dependencies:
  - name: openclaw
    repository: https://serhanekicii.github.io/openclaw-helm
    version: 1.3.18
description: Helm chart to deploy OpenClaw
name: openclaw
version: 1.0.0
