openclaw:
    app-template:
        controllers:
            main:
                containers:
                    main:
                        env:
                            GEMINI_API_KEY: ENC[AES256_GCM,data:ebtmx4fOmp8jU2JJXhf3Tu/soahA0DdEm5iaEcaPo7C+LWxpP4+h,iv:/h2YPlC9YHIwhqHFsYAJZ3HMUn6bCJ2yuaEozJ6qTes=,tag:4jmx7fSH774yNeIg/+eYMw==,type:str]
                            OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:ugS4rUsZaw/Qb45Y4e5t2PsY6Ov8Lwg2HQ==,iv:dE9xLNIfReEzAdAhozhmruMGqiJA206m8J8+0oBUneI=,tag:ZVP9kB6CMf5UxkQkiJ3Fbg==,type:str]
                            MOONSHOT_API_KEY: ENC[AES256_GCM,data:FpBXJeInyAeMvrunHIJnpAnOSR7CMDrF+gv4+KFebpZRN9zq8pTxW6u1ZWolv8BDNvlYN6OYrjvJaftdq1Rpq/Rdg50RMA==,iv:92SomOofhyszk4F8CEHekWqQtUJc3MFKM6WDsxYuXlg=,tag:VtAMsd/4zfKwK3ZS89MdxA==,type:str]
sops:
    age:
        - recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbk5rSGswUzBjYmZhaDk4
            MTVCRjJFSTlxampDWElxR0xQUWhMZm45akJRCkt6L2VRbXowNjFZOE1xeENYV014
            NkVDYW0yZ2V6MmhOYVBQZDFaTFFXelkKLS0tIHNZckY4YW1xUVZBck16eTV3aWg0
            Y29FK05hd0t2NUY4V2llOERTYUlJYncKpm5SFdxA49thDQzEJpu65o9l0k7W4ETd
            hrsXrU1CKDtxxS0EYMcwJnxRzqWmQ+oQwVtahUpyMhp97mQ++zRAPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMjdjVVB0YVRaa3FTV2pz
            VUFXMWpVRTVxN29TRCtLdk9lQjE1Uy9wMDNnClJLU1dLK1R2SDJTaUdzYXJqYnMr
            SjhaOTE4WGtDQ29RNGVBSUxSbng4NzQKLS0tIDFhbmRWUkpYeC80VkdpQ2ZOYXZp
            d1FsVzlIRGNkMFcvSXpqKytXUUZ1OTgKjNRYKxyXaJ7HU7EYt2bzkRBgyIoo9NlV
            0OUQpAjue0tp+gnFcBwFvzjlmI6Cuy0pbaXhz8ZLTWfq1y1Ec2LFSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T17:37:02Z"
    mac: ENC[AES256_GCM,data:XQ1sh0K6N6VZKnj5cqxa0XVaImbEtxq2Zk5eqfjy0+Ps/GlhEGAQE3cIxYwK+iIYpFwFT2OwAahKBuH47Uxsy1dtEegOrohD+Lf63Zen6ADZD0JYMRbiiK019Ocv8LiwcBVK7pSRLWyJfg9Ec2x42BEHWrw6L3TeSczLbHv+H3Q=,iv:Ob36xs0OFjEQW/SXwb/X9fcUEBvz2A0JgK7fnciOLII=,tag:T4g57SteC1HYzQvIIVZs5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
