image:
  repository: ghcr.io/advplyr/audiobookshelf
  tag: 2.32.1
persistence:
  audiobookshelf:
    config:
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    metadata:
      size: 10Gi
      accessModes:
        - ReadWriteOnce

  shelfmark:
    config:
      size: 1Gi
      accessModes:
        - ReadWriteOnce

  shared:
    audiobooks:
      size: 20Gi
      storageClassName: nfs
      accessModes:
        - ReadWriteMany

    podcasts:
      size: 10Gi
      storageClassName: nfs
      accessModes:
        - ReadWriteMany

    books:
      size: 10Gi
      storageClassName: nfs
      accessModes:
        - ReadWriteMany
