apiVersion: v2
name: prowlarr
description: A Helm chart for prowlarr apps
dependencies:
  - name: app-template
    version: 4.6.2
    repository: oci://ghcr.io/bjw-s-labs/helm
type: application
version: 1.0.0