app-template:
    controllers:
        prowlarr:
            containers:
                app:
                    env:
                        PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:OVt6+W8liACmvDXsLBSP1IIpGpWPLPCEg3fzWUbWb9Y=,iv:ugGzlnWGJjUzvYLrOeclFvzZmqYgWYYscfOJWjXtDEA=,tag:yxrZELD6VjptzwILxB7KuQ==,type:str]
sops:
    age:
        - recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdXBZZDhHM3VRSnBpbmM0
            WGQrQ0NxbENCUEZPL1cwWlZGTGx2SFdNR2swCkwxNTlac09PdFMrbm5DY05YYWdT
            SHBwVkdENVVrcnBZTFJhK2NtQVFYREUKLS0tIGFtRUEyYTNHR0RHV1V4OEF4UlJ1
            cjNRVHluWlJ3cWQ2dHJ5ZmovVHFxT2cKSiQBil0KmQ3gxhX/TQcGdCGeRwQsgPzK
            FpHI3UL/7XGemK29w3a0V/pr1++h5ZhQsjErZWu4MWuBM2bxCBNouA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudjE2RU1hQmdKY1BnOGc0
            VW05ckcyQWRQd0NPQlhuTUVjTTRKZ1BFczA0Cm9rcTNPWGhmYkZMNXEzenFjdmlu
            eXp6N0o4aXl0RStKWWMvcFBvS05pWnMKLS0tIGFSZEpXWnFhVUxkdGYzWUFVNENL
            ZEYvdjZIK0ZNNnRTZkNwWU9wSVhtMjAKQ/8M0fsK+cId05zraHE6LJg3YQuMTXSH
            v7UJtiCbiuacj+bWQlF6YPjVOheL6Ux6IX1s80IIsFaL1TWlK5Rcwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T13:12:54Z"
    mac: ENC[AES256_GCM,data:3k1FZtfD9NcOMEO/Hk7j3ZoF/dpCNXBo9AVeXpZhQAI6yaSnrCM9UIHQd3AOGKcJFZwTdW4l6lbFs5/EjoE+qM5jMNTMyteJrxQpqZ1KQ0Axxkm1mhLNI+2PSZpo6YfEaCJ4FGFwAT/NjcfRVM7r/AUkbQ2afmyrCpvRbOyi3yI=,iv:ENTvx3xHSCogRUFRk4C/ED4fCsIPrVZfoIM9zI9H26g=,tag:OM8raRSj67NhgChIacsUuQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
