appTemplate:
    controllers:
        prowlarr:
            containers:
                app:
                    env:
                        PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:myrKdLceJ/2dzZS+864gMlLEYkh53n7r4A0a1JUJc8s=,iv:VmMIg2EggGnNE1IHFERpwWUktKPt0TRrLUaMon3SxE4=,tag:9HnIIIgAJbfCQVRXniETjw==,type:str]
sops:
    age:
        - recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdXBZZDhHM3VRSnBpbmM0
            WGQrQ0NxbENCUEZPL1cwWlZGTGx2SFdNR2swCkwxNTlac09PdFMrbm5DY05YYWdT
            SHBwVkdENVVrcnBZTFJhK2NtQVFYREUKLS0tIGFtRUEyYTNHR0RHV1V4OEF4UlJ1
            cjNRVHluWlJ3cWQ2dHJ5ZmovVHFxT2cKSiQBil0KmQ3gxhX/TQcGdCGeRwQsgPzK
            FpHI3UL/7XGemK29w3a0V/pr1++h5ZhQsjErZWu4MWuBM2bxCBNouA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudjE2RU1hQmdKY1BnOGc0
            VW05ckcyQWRQd0NPQlhuTUVjTTRKZ1BFczA0Cm9rcTNPWGhmYkZMNXEzenFjdmlu
            eXp6N0o4aXl0RStKWWMvcFBvS05pWnMKLS0tIGFSZEpXWnFhVUxkdGYzWUFVNENL
            ZEYvdjZIK0ZNNnRTZkNwWU9wSVhtMjAKQ/8M0fsK+cId05zraHE6LJg3YQuMTXSH
            v7UJtiCbiuacj+bWQlF6YPjVOheL6Ux6IX1s80IIsFaL1TWlK5Rcwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T08:44:45Z"
    mac: ENC[AES256_GCM,data:bTZK3yDVOtYlOOL7J70xShoOEYWx4EpE1jqYpe+qw738X/cr5qPV5P8USV6SqoYucaXxWlHFxhOrZ8I67/GkQmEINfT2TWeo/l28/05pOCI9HpOF1eRj7LRL+KUTWmyFy0YOcgtozcJXJRGWT93fR5v8b5vg71zDyvXBOEKjhN0=,iv:hO+Xo90owSSeNgFhwIvPprlBXiJ1MjnIabu52mZ7HpY=,tag:ruYUHKUl/HUKnRRnuVckww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
