app-template:
    controllers:
        prowlarr:
            containers:
                app:
                    env:
                        PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:7Xs3wcMWVO8LsyxE3KiksBQABHKH9hBfgFnD3gn4AtU=,iv:X7Bld1ERslpxh7Mvi7grof2U+e+L31FGLvpg5nM2RKg=,tag:oodJcQzRZShUuwpR4GqW+A==,type:str]
sops:
    age:
        - recipient: age1hnmh393g3qaf2szdjkyrd7jsven9wzvgpud4207vzrfywmuvdassvperqc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdXBZZDhHM3VRSnBpbmM0
            WGQrQ0NxbENCUEZPL1cwWlZGTGx2SFdNR2swCkwxNTlac09PdFMrbm5DY05YYWdT
            SHBwVkdENVVrcnBZTFJhK2NtQVFYREUKLS0tIGFtRUEyYTNHR0RHV1V4OEF4UlJ1
            cjNRVHluWlJ3cWQ2dHJ5ZmovVHFxT2cKSiQBil0KmQ3gxhX/TQcGdCGeRwQsgPzK
            FpHI3UL/7XGemK29w3a0V/pr1++h5ZhQsjErZWu4MWuBM2bxCBNouA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mm90zkg8lsmpqa7gya9p2prsj8yfq774gjm6dkamkkvwugen7ywse5w97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudjE2RU1hQmdKY1BnOGc0
            VW05ckcyQWRQd0NPQlhuTUVjTTRKZ1BFczA0Cm9rcTNPWGhmYkZMNXEzenFjdmlu
            eXp6N0o4aXl0RStKWWMvcFBvS05pWnMKLS0tIGFSZEpXWnFhVUxkdGYzWUFVNENL
            ZEYvdjZIK0ZNNnRTZkNwWU9wSVhtMjAKQ/8M0fsK+cId05zraHE6LJg3YQuMTXSH
            v7UJtiCbiuacj+bWQlF6YPjVOheL6Ux6IX1s80IIsFaL1TWlK5Rcwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:56:26Z"
    mac: ENC[AES256_GCM,data:jxAqz6M1sLOtiTAM3N7dferFZskib2AktunPIMexCg+Z9X9VEOWbE8/aX5iyhVmbRZDo2k+cggo9eSSZQko8OaQ4n/ZctC7f8ce50tHMV3KrTIWGpIEQKkZXXVpcwLb6f278gzvEid8qk4IPxfo/I9T4NtD62iHNX5uMxWcHCFQ=,iv:3XV4gVlvqukjJ88TZ2Ou8gRqJT/vNOL/VlLHJ05X4xY=,tag:Ninux0Nyd2+pYnrvQro0QQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
