apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - "audiobooks.blarc.my.id"
  rules:
    - backendRefs:
        - name: audiobookshelf
          port: {{ .Values.service.port }}
      matches:
        - path:
            type: PathPrefix
            value: /
