apiVersion: v1
kind: Secret
metadata:
    name: providers-secrets
    namespace: {{ .Release.Namespace | default "authentik" }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.providersSecrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}