apiVersion: v1
kind: Secret
metadata:
    name: users-passwords
    namespace: {{ .Release.Namespace | default "authentik" }}
type: Opaque
stringData:
  {{- range $user := .Values.users }}
  {{ $user.username | upper }}_PASSWORD: {{ $user.password | quote }}
  {{ $user.username | upper }}_EMAIL: {{ $user.email | quote }}
  {{- end }}