apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name paperless-ngx
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: gateway-internal
      namespace: gateway
  hostnames:
    - "paperless.blarc.my.id"
  rules:
    - backendRefs:
        - name: *name
          port: 8000
      matches:
        - path:
            type: PathPrefix
            value: /
