apiVersion: apps/v1
kind: Deployment
metadata:
  name: cod2
  namespace: default
  labels:
    app: cod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cod2
  template:
    metadata:
      labels:
        app: cod2
    spec:
      containers:
        - name: cod2
          image: registry.int.blarc.my.id/cod2:latest
          ports:
            - containerPort: 20500
              protocol: UDP
            - containerPort: 20510
              protocol: UDP
            - containerPort: 28960
              protocol: TCP
            - containerPort: 28960
              protocol: UDP
          args:
            [
              "+set",
              "net_port",
              "28960",
              "+set",
              "sv_cheats",
              "0",
              "+set",
              "sv_punkbuster",
              "0",
              "+exec",
              "punkbuster.cfg",
              "+exec",
              "server_mp.cfg"
            ]
          stdin: true
          tty: true
          volumeMounts:
            - name: server-config
              subPath: server_mp.cfg
              mountPath: /home/cod2/main/server_mp.cfg
      volumes:
        - name: server-config
          secret:
            secretName: cod2-server-mp
