apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shelfmark
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: gateway-internal
      namespace: gateway
  hostnames:
    - "shelfmark.blarc.my.id"
  rules:
    - backendRefs:
        - name: shelfmark
          port: 8084
      matches:
        - path:
            type: PathPrefix
            value: /
