apiVersion: v1
kind: Secret
metadata:
  name: shelfmark
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  HARDCOVER_API_KEY: "{{ .Values.hardcover.apiKey }}"
  PROWLARR_API_KEY: "{{ .Values.prowlarr.apiKey }}"