apiVersion: v2
dependencies:
  - name: lvm-disk-watcher
    repository: oci://oci.trueforge.org/truecharts
    version: 4.2.5
description: Helm chart to deploy lvm-disk-watcher
name: lvm-disk-watcher
version: 1.0.0
