lvm-disk-watcher:

  image:
    repository: oci.trueforge.org/tccr/lvm-disk-watcher
    pullPolicy: IfNotPresent
    tag: v1.1.9

  configmap:
    disk-config:
      enabled: true
      data:
        disk-config: |
          control-plane-1: none
          worker-1: all
