apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: blog
  namespace: blog
spec:
  parentRefs:
    - name: internal
      namespace: traefik
  hostnames:
    - "blog.blarc.my.id"
  rules:
    - backendRefs:
      - name: blog
        port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
