apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: traefik
  listeners:
    - protocol: HTTP
      port: 8000
      name: web
      hostname: "*.blarc.my.id"
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 8443
      name: websecure
      hostname: "*.blarc.my.id"
      tls:
        certificateRefs:
          - kind: Secret
            name: internal-certificate
            # Keep this for argo
            group: ''
      allowedRoutes:
        namespaces:
          from: All
