apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: external
      namespace: traefik
  hostnames:
    - "immich.blarc.my.id"
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}-server
          port: 2283
      matches:
        - path:
            type: PathPrefix
            value: /