apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
type: Opaque
stringData:
    admin-password: "{{ .Values.admin.password }}"
    admin-user: "{{ .Values.admin.username }}"
