apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ntfy
  namespace: ntfy
spec:
  parentRefs:
    - name: gateway-external
      namespace: gateway
  hostnames:
    - "ntfy.blarc.my.id"
  rules:
    - backendRefs:
      - name: ntfy
        port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
