apiVersion: v1
kind: Secret
metadata:
  name: ntfy
  namespace: {{ .Release.Namespace }}
stringData:
  NTFY_AUTH_USERS: {{ range $index, $user := .Values.users -}}
    {{- if $index }},{{ end -}}
    {{- $user.name }}:{{ $user.passwordHash }}:{{ $user.role -}}
  {{- end }}