apiVersion: v2
dependencies:
  - name: kube-prometheus-stack
    repository: oci://ghcr.io/prometheus-community/charts
    version: 81.6.1
description: Helm chart to deploy kube-prometheus-stack
name: kube-prometheus-stack
version: 1.0.0
