apiVersion: v1
kind: Secret
metadata:
    name: alertmanager
    namespace: {{ .Release.Namespace }}
stringData:
    NTFY_URL: "{{ .Values.alertmanager.ntfyUrl }}"
    NTFY_USERNAME: "{{ .Values.alertmanager.ntfyUsername }}"
    NTFY_PASSWORD: "{{ .Values.alertmanager.ntfyPassword }}"
